#!/usr/bin/env bash

# Set some needed CI values
if [ -n "$CI" ]; then
  # Abort the script if there is a non-zero error
  set -e

  if [ -n "$GITHUB_EMAIL" ]; then
    git config --global user.email "$GITHUB_EMAIL" > /dev/null 2>&1
  fi

  if [ -n "$GITHUB_NAME" ]; then
    git config --global user.name "$GITHUB_NAME" > /dev/null 2>&1
  fi
fi

remote=$(git config remote.origin.url)

echo "Deploying https://johanbrook.com"
echo ""
echo "* Deploying commit:"
echo "  $(git log -n 1)"

# Jump into pre-built site
cd ./build
# Get some important files over
cp ../CNAME ./CNAME
touch ./.nojekyll

# Create a new repo solely for deploying
git init . -q

if [ -n "$CI" ]; then
  git remote add origin "$remote"
fi

git add .
git commit -m "⬆️ Deploy [`date`] [ci skip]" --quiet
git log -n 1
git push origin master:gh-pages --force
rm -rf .git
cd -

echo "* Site deployed to https://johanbrook.com"
