name = "johans-functions"
account_id = "96a73ee8d5a6a04f37dd5136d875497e"
compatibility_flags = []
workers_dev = true
compatibility_date = "2023-04-11"

# Secrets:
# github-oauth
#   ADMIN_CLIENT_SECRET
#   ADMIN_CLIENT_ID
# post-note:
#   SHORTCUT_TOKEN
#   SHORTCUT_PASSWORD
# music:
#   LASTFM_API_KEY
