#!/usr/bin/env deno run --no-check --allow-read --allow-write --allow-run

/*
    Usage:

        ./script/new-post "This is a title"

    Will create the file with a template and open it in VS Code. The filename
    will follow the template: [yyyy-MM-dd]-[slugified-title].md.
*/

import * as datetime from 'datetime';

const DEST = Deno.cwd() + '/src/posts';

const d = new Date();
const offset = Math.abs(d.getTimezoneOffset()) / 60;

const title = Deno.args[0] ?? 'New post';
const slug = title.toLowerCase().replace(/\s+/g, '-').trim();
const date = datetime.format(d, `yyyy-MM-dd HH:mm:ss '+${offset}'`);
const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;

const TEMPLATE = `---
title: ${title}
slug: ${slug}
date: ${date}
location: <where>
timezone: ${timezone}
excerpt: <excerpt>
tags:
  - key
draft: true
---\n
`;

const fileName = `${datetime.format(d, 'yyyy-MM-dd')}-${slug}.md`;
const fullPath = DEST + '/' + fileName;

await Deno.writeTextFile(fullPath, TEMPLATE, {
    append: true,
});

console.log(`Created ${fullPath}`);

const editor = Deno.run({
    cmd: ['zed', fullPath],
    stdout: 'piped',
    stderr: 'piped',
});

const { code } = await editor.status();
const rawError = await editor.stderrOutput();

if (code != 0) {
    const errorString = new TextDecoder().decode(rawError);
    console.log('Error from process: ', errorString);
}

editor.close();

Deno.exit(code);
