#!/usr/bin/env deno run --no-check --allow-read --allow-write --allow-run --unstable-temporal

/*
    Usage:

        ./script/new-post "This is a title"

    Will create the file with a template and open it in VS Code. The filename
    will follow the template: [yyyy-MM-dd]-[slugified-title].md.
*/

import { formatFileName, formatISO } from '../api/date.ts';

const DEST = Deno.cwd() + '/src/posts';

const title = Deno.args[0] ?? 'New post';
const slug = title.toLowerCase().replace(/\s+/g, '-').trim();

const zonedDateTime = Temporal.Now.zonedDateTimeISO(); // now, in current timezone

// I want both of these to be in the *local* time:

// Will go into the frontmatter:
const metaDate = formatISO(zonedDateTime);
// Will be the filename:
const fileDate = formatFileName(zonedDateTime);

const TEMPLATE = `---
title: ${title}
slug: ${slug}
date: ${metaDate}
location: <where>
timezone: ${zonedDateTime.timeZone}
excerpt: <excerpt>
tags:
    - key
draft: true
---\n
`;

const fileName = `${fileDate}-${slug}.md`;
const fullPath = DEST + '/' + fileName;

await Deno.writeTextFile(fullPath, TEMPLATE, {
    append: true,
});

console.log(`Created ${fullPath}`);

const editor = Deno.run({
    cmd: ['zed', fullPath],
    stdout: 'piped',
    stderr: 'piped',
});

const { code } = await editor.status();
const rawError = await editor.stderrOutput();

if (code != 0) {
    const errorString = new TextDecoder().decode(rawError);
    console.log('Error from process: ', errorString);
}

editor.close();

Deno.exit(code);
