#!/usr/bin/env deno run --no-check --allow-read --allow-write --allow-run

/*
    Usage:

        ./script/new-post "This is a title"

    Will create the file with a template and open it in VS Code. The filename
    will follow the template: [yyyy-MM-dd]-[slugified-title].md.
*/

import { formatDate } from './util.js';

const DEST = Deno.cwd() + '/src/posts';

const title = Deno.args[0] ?? 'New post';
const slug = title.toLowerCase().replace(/\s+/g, '-').trim();
const date = formatDate(new Date(), 'yyyy-MM-dd');

const TEMPLATE = `---
title: ${title}
slug: ${slug}
date: ${date}
location: <where>
excerpt: <excerpt>
keywords:
  - key
draft: true
---\n
`;

const fileName = `${date}-${slug}.md`;
const fullPath = DEST + '/' + fileName;

await Deno.writeTextFile(fullPath, TEMPLATE, {
    append: true,
});

console.log(`Created ${fullPath}`);

const editor = Deno.run({
    cmd: ['code', fullPath], // XXX Can't use shell variable $EDITOR here :(
    stdout: 'piped',
    stderr: 'piped',
});

const { code } = await editor.status();
const rawError = await editor.stderrOutput();

if (code != 0) {
    const errorString = new TextDecoder().decode(rawError);
    console.log('Error from process: ', errorString);
}

Deno.exit(code);
