author: Johan Brook
avatar: /.well-known/avatar.jpg

description: I'm a thirty-something designer and developer based in Sweden. I work
    with the best people in a company called Lookback, where I help interfaces come
    to life. I'm coding & designering and I like working with product, user experience,
    interface design, and other things too.
shortbio: I'm coding & designering, and I like working with product.
site: https://johan.im
github: johanbrook
repo: johanbrook/johanbrook.com
location:
    city: Stockholm
    country: Sweden
mastodon:
    username: brookie
    instance: hachyderm.io
    domain: johan.im
email: webmaster@johan.im
cv: /johanbrook-cv.pdf
currentVersionOfJohan: 4.0.0
