name: Build and Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup deno and lume
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.17.x

      - name: Install and Build site
        env:
          CI: true
          NODE_ENV: production
          ENV: production
        run: deno run -A https://deno.land/x/lume@v1.3.1/ci.ts --location=https://johanbrook.com --quiet

      - name: Save build dir
        uses: actions/upload-artifact@v2
        with:
            name: built-site
            path: build
            retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == 'main'
    steps:
      - name: Download built site
        uses: actions/download-artifact@v2
        with:
          name: built-site
      - name: Deploy to GitHub Pages
        if: github.ref_name == 'main'
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # The branch the action should deploy from.
          BASE_BRANCH: main
          # The branch the action should deploy to.
          BRANCH: gh-pages
          # The folder the action should deploy.
          FOLDER: build

      - name: Purge Cloudflare cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
