name: Build & Deploy johanbrook.com

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Build, Test and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          CI: true
          NODE_ENV: production
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          # The branch the action should deploy from.
          BASE_BRANCH: master
          # The branch the action should deploy to.
          BRANCH: gh-pages
          # The folder the action should deploy.
          FOLDER: build
          # The build script the action should run prior to deploying.
          BUILD_SCRIPT: npm install --no-save --no-audit && npm test && npm run build
          CNAME: johanbrook.com

      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
